### ISSUE TITLE
Bad Request - Invalid BusinessShortCode

### ISSUE THREAD

**Issue by joelkanyi** [jumaallan/android-daraja-sdk#80]
**Describe the bug**
I created a small demo and tried using the library but I keep getting this exception below. I went ahead and cloned this repo and executed it on my Android Studio but still the same exception. I then went ahead and replaced the credential with mine, but still the same error.

`com.androidstudy.daraja.callback.DarajaException: 400.002.02 : Bad Request - Invalid BusinessShortCode`

**To Reproduce**
1. Run the demo once you clone this repo
2. Input your phone number and amount
3. Click on Pay Button
4. The error will be toasted

**Comment by jumaallan** [comment]
Should be fixed by PR #81

**Comment by Mosericko** [comment]
Still getting the same error even after the fix.  
`exception: 400.002.02 : Bad Request - Invalid BusinessShortCode`  
Any help would be greatly appreciated

**Comment by jumaallan** [comment]
> Still getting the same error even after the fix. `exception: 400.002.02 : Bad Request - Invalid BusinessShortCode` Any help would be greatly appreciated

My bad

Need to do a new release. 

@wangerekaharun

**Comment by Mosericko** [comment]
Haha no worries, thanks
